# Site settings
title: MJ Design
email: michael@formationtech.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Michael James Phillips, this is MJ Design.
baseurl: ""
url: "http://mjdesign/mjdesign.github.io"
twitter_username:
github_username:

markdown:
